課題③-4を実装
kei0722/assignment_js_3-4 pull request #1
Opened 2020-08-07 09:48 UTC by kei0722

2020-08-07 11:33 UTC, myzktkyk requested changes
動作は問題ありませんでした。
コードの書き方について指摘をしています。

2020-08-07 11:33 UTC, myzktkyk commented on js/main.js
> +					tbody.children[i].style.display = "none";
`display = "none"` を操作するコードがいろいろな所に記述されてしまっていて
全体の見通しが悪くなってしまっています。

以下のように考えてみてはいかがでしょうか？

1. showTodoList を改修する
- 引数を追加してラジオボタンの値(`status`)を受け取れるようにする
- 受け取った引数(`status`)と合致する todo だけを HTML(tbody)に変換する

2. ラジオボタン に change イベントを定義し、`showTodoList` を呼び出すようにする。

2020-08-24 13:28 UTC, Dok1211 commented on js/main.js
> +function createTodoWorkingon() {
キャメルケースにするならworkingOnですね

2020-08-24 13:28 UTC, Dok1211 commented on js/main.js
> +function createTodoWorkingon() {
functionはアロー関数に置き換えましょう
https://qiita.com/may88seiji/items/4a49c7c78b55d75d693b

2020-08-24 13:28 UTC, Dok1211 commented on js/main.js
> +	while(tbody.firstChild) {
whileと(の間に半角スペースを入れましょう

2020-08-24 13:28 UTC, Dok1211 commented on js/main.js
> +	const todoWorkingon = todoList.filter( aaa => aaa.state === '作業中');
aaaというのは？
何かしらの変数名であれば意味のある命名にしましょう

2020-08-24 13:28 UTC, Dok1211 commented on js/main.js
> +	const todoWorkingon = todoList.filter( aaa => aaa.state === '作業中');
作業中
というのと
working on
というのが混在しているので統一しましょう
例えば
```
const TYPE = {
  ALL: '全て',
  DOING: '作業中',
  DONE: '完了'
}
```
こんな風に定義して
TYPE.DOING
のように呼び出してしまえば表記がブレなくなります

2020-08-24 13:28 UTC, Dok1211 commented on js/main.js
> +	for(let i = 0; i < getStateButton.length; i++) {
forと(の間に半角スペースを入れましょう

2020-08-24 13:28 UTC, Dok1211 commented on js/main.js
> +		getStateButton[i].addEventListener("click", () => {
"と'が混在しているので特別な理由がない限り統一しましょう

2020-08-24 13:28 UTC, Dok1211 commented on js/main.js
> +		delete: '削除',
ここは変動しないのでtodoごとに持たせなくてもいいと思います

2020-08-24 13:28 UTC, Dok1211 commented on js/main.js
> +	for (let i = 0; i < test01.length; i++) {
if文の中にif文を入れたり
for文の中にfor文を入れるとネストが深くなって読みにくくなります
なるべくシンプルになるように工夫してみましょう
https://qiita.com/DeployCat/items/1ec901864d4ab11c8d6f

ループであればforeachもうまく利用してみましょう

2020-08-25 14:59 UTC, kei0722 commented on js/main.js
> +		delete: '削除',
ご指摘内容が理解できなかったのですが、もう少し詳しく教えていただけないでしょうか？
理解不足で申し訳ありません。

2020-08-27 13:56 UTC, Dok1211 commented on js/main.js
> +	const todoWorkingon = todoList.filter( todoListfiltered => todoListfiltered.state === TYPE.DOING);
todoListfilteredはキャメルケースにすると
todoListFilteredですね
あとtodoWorkingonのキャメルケースにしましょう

2020-08-27 13:56 UTC, Dok1211 commented on js/main.js
> +		document.querySelectorAll('th').forEach( function() {
いくつかfunctionがのこっていますが、アロー関数に置き換えましょう

2020-08-27 13:56 UTC, Dok1211 commented on js/main.js
> +	const todoWorkingon = todoList.filter( todoListfiltered => todoListfiltered.state === TYPE.DOING);
そもそもですが、fileteredという命名なのねフィルタリングされる前の状態なので命名として違和感があります
あと長いので適切な箇所で改行、半角スペースを削ると
```
const todoWorkingOn = todoList.filter(todoList =>
	todoList.state === TYPE.DOING
);
```
こんな感じになります

2020-08-27 13:56 UTC, Dok1211 commented on js/main.js
> +			} else if (options[i].value === 'COMPLETED') {
COMPLETEDになっていますがradio buttonではDONEになっています
また、elseifが連続する場合はswitch文にしたほうが見やすくなります

2020-08-28 14:13 UTC, kei0722 commented
a

2020-08-28 14:14 UTC, kei0722 commented
・変数名を修正
・ラジオボタンの値を変更
・functionをアロー関数へ

2020-10-10 16:39 UTC, closed without merging